version: "3"

services:
  python3:
    restart: always
    build: .

    container_name: "python3"
    working_dir: "/work/"
    tty: true
    volumes:
      - ./:/work/
    ports:
      - "8000:8000"

  nginx:
    container_name: python3-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8000:8000
